import type { Metadata } from "next";
import {Outfit} from 'next/font/google'
import "./globals.css";

const outfity = Outfit({subsets:['latin']})
export const metadata: Metadata = {
  title: "CashTraker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={`${outfity.className} bg-white text-black`}
      >
        {children}
      </body>
    </html>
  );
}
